### ISSUE TITLE
Fail Gracefully When Solver Not Available

### ISSUE THREAD

**Issue by jdecarolis** [hunteke/temoa#14]
I initially forgot to install a solver, and the Pyomo-based error message was unclear. It would be nice if the Temoa code recognized that a solver was not present before it ran and returned a helpful error message.

**Comment by hunteke** [comment]
a06bb82f50bdf5ba4d5467581d3c44d5772aaac3
d31c801354d9f851c33329c689af742b1c20503b

Addressed with these two commits.  Naughty me didn't fully separate out d31c801, unfortunately.  Hooray for crunch times!

Temoa currently does not fail directly, but attempts to inform the user by pausing before doing any work if a solver has not been chosen.  Since we auto choose the "best" solver from what Coopr finds, this _should_ be enough for most users.  We'll find out.
