### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by blanzy** [hunteke/temoa#40]
It might perhaps be useful to also include the results obtained with temoa using the datasets supplied?

**Comment by hunteke** [comment]
I'm not clear on what it is you are asking.  Do you mean to include in the repository a `results/` directory such that when folks clone the repo, they have an already-solved version of the results?

**Comment by blanzy** [comment]
Yes, exactly. The thought being that a user who has installed Temoa and run
a test case has a benchmark to compare against and know that his
installation is working as it should.....

**Comment by hunteke** [comment]
Your idea has merit, but I'm actually working on a different mechanism to share datasets.  We intend this new mechanism to be more user friendly (a tough road to travel given Temoa's current command line oriented nature!) and accessible by more than just those who feel comfortable getting their hands dirty with Git.

I won't say much here (because I'm still at the pre-pre-pre-alpha stage with it), but the hint I'll drop is to "peruse all of the branches in this repository".
